export const userdata = [
  {
    id: 1,
    email: 'adminjude@quickcredit.com',
    firstName: 'jude',
    lastName: 'ezekiel',
    password: '$2b$12$Ky0BRqWtU1iDRTWbD6W5g.qjB741a1Ke5jrcWZ0.YheB44re5fBVm',
    address: '2 ikpoh street',
    status: 'verified',
    isAdmin: true,
  },
  {
    id: 2,
    email: 'andela@gmail.com',
    firstName: 'Andela',
    lastName: 'anthony',
    password: '$2b$12$.PBmTYCHeluKXK.hF/Z14ehY1499NTAIiw51h8qohXOMKwCog1juK',
    address: '34 anthony road',
    status: 'unverified',
    isAdmin: false,
  },
  {
    id: 3,
    email: 'andela2@gmail.com',
    firstName: 'Andela',
    lastName: 'anthony',
    password: '$2b$12$.PBmTYCHeluKXK.hF/Z14ehY1499NTAIiw51h8qohXOMKwCog1juK',
    address: '34 anthony road',
    status: 'unverified',
    isAdmin: false,
  },
  {
    id: 4,
    email: 'andela3@gmail.com',
    firstName: 'Andela',
    lastName: 'anthony',
    password: '$2b$12$.PBmTYCHeluKXK.hF/Z14ehY1499NTAIiw51h8qohXOMKwCog1juK',
    address: '34 anthony road',
    status: 'unverified',
    isAdmin: false,
  },
  {
    id: 5,
    email: 'andela4@gmail.com',
    firstName: 'Andela',
    lastName: 'anthony',
    password: '$2b$12$.PBmTYCHeluKXK.hF/Z14ehY1499NTAIiw51h8qohXOMKwCog1juK',
    address: '34 anthony road',
    status: 'unverified',
    isAdmin: false,
  },
];

export const loanData = [{
  id: 'Integer',
  user: 'String',
  createdOn: 'DateTime',
  status: 'String',
  repaid: 'Boolean',
  tenor: 'Integer',
  amount: 'Float',
  paymentInstallment: 'Float',
  balance: 'Float',
  interest: 'Float',
},
];
